apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rundeck-job-template-porthedland
  title: Deploy AWS Resources (Porthedland)
  description: Use this template to deploy EC2 host resources as userporthedland.
  tags:
    - rundeck
    - job
    - automation
spec:
  owner: user-porthedland
  type: rundeck-orchestration

  parameters:
    - title: Deploy Multicloud Resources
      required:
        - environment
        - region
        - ami
        - ttl
        - userTag
        - instanceType
      properties:
        environment:
          title: Environment
          type: string
          description: Target environment for the job
          enum:
            - dev
            - staging
            - prod

        region:
          title: Region
          type: string
          description: Target AWS region
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1

        ami:
          title: Sample AMI
          type: string
          description: >
            The Amazon Machine Image (AMI) ID to deploy. For example, use 'ami-0abcdef1234567890' for an Ubuntu 20.04 LTS image.
          default: ami-05b10e08d247fb927

        ttl:
          title: Time to Live (TTL)
          type: string
          description: >
            Duration in days before the resource is automatically deleted. Choose one of the following options: 7, 14, or 30 days.
          enum:
            - "7"
            - "14"
            - "30"
          default: "7"

        userTag:
          title: User Tag
          type: string
          description: >
            Custom tag to identify the owner of the resource.
          default: user-porthedland

        instanceType:
          title: AWS Instance Type
          type: string
          description: >
            AWS instance sizing for the EC2 host. Choose an instance type such as t2.micro, t2.small, t2.medium, t3.micro, t3.small, or t3.medium.
          enum:
            - t2.micro
            - t2.small
            - t2.medium
            - t3.micro
            - t3.small
            - t3.medium
          default: t2.micro

        waitForJob:
          title: Wait for completion
          type: boolean
          description: Wait for job to complete before finishing
          default: true

  steps:
    - id: rundeck-execute
      name: Execute Rundeck Job
      action: rundeck:job:execute
      input:
        jobId: 'aws-provisioning-user-porthedland'
        projectName: NA
        parameters:
          ENV: ${{ parameters.environment }}
          REGION: ${{ parameters.region }}
          AMI: ${{ parameters.ami }}
          TTL: ${{ parameters.ttl }}
          USER_TAG: ${{ parameters.userTag }}
          INSTANCE_TYPE: ${{ parameters.instanceType }}
        waitForJob: ${{ parameters.waitForJob }}

    - id: log-results
      name: Display Deployment Results
      action: debug:log
      input:
        message: |
          ===== Rundeck Job Execution Complete =====
          Status: ${{ steps['rundeck-execute'].output.status }}
          Execution ID: ${{ steps['rundeck-execute'].output.executionId }}

          Environment: ${{ parameters.environment }}
          Region: ${{ parameters.region }}
          Instance Type: ${{ parameters.instanceType }}
          TTL: ${{ parameters.ttl }} days

          ===== Execution Logs =====
          ${{ steps['rundeck-execute'].output.logs }}

  output:
    text:
      - title: Execution Logs
        content: ${{ steps['rundeck-execute'].output.logs }}
      - title: Deployment Status
        content: ${{ steps['rundeck-execute'].output.status }}
      - title: Execution ID
        content: ${{ steps['rundeck-execute'].output.executionId }}
      - title: Deployment Parameters
        content: |
          Environment: ${{ parameters.environment }}
          Region: ${{ parameters.region }}
          AMI: ${{ parameters.ami }}
          Instance Type: ${{ parameters.instanceType }}
          TTL: ${{ parameters.ttl }} days
          User Tag: ${{ parameters.userTag }}
